### ISSUE TITLE
Error with Visual C++ for python

### ISSUE THREAD

**Issue by JJBarea** [lkreidberg/batman#14]
I suppose I made some kind of rookie mistake, but this is the error that I get when I try to install the package on windows:  

C:\Users\John\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Users\John\Anaconda2\lib\site-packages\numpy\core\include -IC:\Users\John\Anaconda2\include -IC:\Users\John\Anaconda2\PC /Tcc_src/_nonlinear_ld.c /Fobuild\temp.win-amd64-2.7\Release\c_src/_nonlinear_ld.obj
    _nonlinear_ld.c
    c_src/_nonlinear_ld.c(35) : error C2143: syntax error : missing ';' before 'type'
    c_src/_nonlinear_ld.c(36) : error C2065: 'sqrtmu' : undeclared identifier
    c_src/_nonlinear_ld.c(36) : error C2065: 'sqrtmu' : undeclared identifier
    c_src/_nonlinear_ld.c(36) : error C2065: 'sqrtmu' : undeclared identifier
    c_src/_nonlinear_ld.c(36) : error C2065: 'sqrtmu' : undeclared identifier
    c_src/_nonlinear_ld.c(48) : error C2065: 'M_PI' : undeclared identifier
    c_src/_nonlinear_ld.c(49) : error C2065: 'M_PI' : undeclared identifier
    c_src/_nonlinear_ld.c(66) : error C2143: syntax error : missing ';' before 'type'
    c_src/_nonlinear_ld.c(67) : error C2143: syntax error : missing ';' before 'type'
    c_src/_nonlinear_ld.c(86) : error C2143: syntax error : missing ';' before 'type'
    c_src/_nonlinear_ld.c(93) : error C2065: 'd_array' : undeclared identifier
    c_src/_nonlinear_ld.c(93) : error C2109: subscript requires array or pointer type
    c_src/_nonlinear_ld.c(97) : error C2065: 'f_array' : undeclared identifier
    c_src/_nonlinear_ld.c(97) : error C2109: subscript requires array or pointer type
    c_src/_nonlinear_ld.c(111) : error C2065: 'norm' : undeclared identifier
    c_src/_nonlinear_ld.c(120) : error C2065: 'norm' : undeclared identifier
    c_src/_nonlinear_ld.c(123) : error C2065: 'f_array' : undeclared identifier
    c_src/_nonlinear_ld.c(123) : error C2109: subscript requires array or pointer type
    error: command 'C:\\Users\\John\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

**Comment by lkreidberg** [comment]
Interesting! I haven't personally tried to compile on windows, but I know at least one person has done it successfully. First question - are you using the development version, or the PyPI version? Some of these errors were fixed by #ifndef statements added by the other windows user about two months ago.

**Comment by JJBarea** [comment]
I have tried to install both the dev version and the PyPI version, and I think I got the same errors. Finally, I made it through the installation proccess succesfully by changing some statements of the code of the .c files. I did the following:

-I separated the declarations of "sqrtmu" and "norm" from the assignment of values to them. The problem seems to be related with MSVS: http://stackoverflow.com/questions/7614397/how-can-i-tell-visual-studio-microsofts-c-compiler-to-allow-variable-declaratio

-I didn't use the d_array, f_array and t_array objects. As you proposed in a comment I replaced all "d = d_array[i];" statements with "d = PyFloat_AsDouble(PyArray_GETITEM(ds, PyArray_GetPtr(ds, &i)));". 
I also replaced " f_array[i] = fValue ;" statements with " PyArray_SETITEM(flux, PyArray_GetPtr(flux, &i),PyFloat_FromDouble(fValue)); ".

-I moved all declaration statements at the begining of every fundtion, although this is probably not necessary.

I am not sure yet whether the package still works as it was supposed to, but at least it was installed successfully.

**Comment by lisadang27** [comment]
Thank you JJBarea for figuring this out! Although, I still get the following errors:
c_src/_nonlinear_ld.c(49) : error C2065: 'M_PI' : undeclared identifier
c_src/_nonlinear_ld.c(50) : error C2065: 'M_PI' : undeclared identifier
c_src/_nonlinear_ld.c(88) : error C2065: 'M_PI' : undeclared identifier
After taking a look at the .c files, M_PI is indeed not declared (using the PyPl version), I was wondering how you solved for this.

**Comment by lkreidberg** [comment]
Glad to hear you got it working! I think these changes should be fine for the functionality of the code. But I'm going to keep the dev version as is (esp the d = d_array[i] statements), because the performance is better and the majority of users are on Mac/Linux, where this works.

**Comment by madisontbrady** [comment]
@IonMich , do you happen to have a copy of the code with your bugfixes still in it?  Could you post it?  I have a similar issue.  Thank you!
